baseURL: http://picozai.tk
languageCode: zh
defaultContentLanguage: zh
title: æ³æ—
theme: PaperMod
googleAnalytics: G-PXWR16MJZH
params:
    homeInfoParams:
        Title: Piacere! ğŸ‘‹
        Content: åœ¨å—æ–¹çš„è¿™é‡Œæœ‰ä¸€ç‰‡æ³æ—ã€‚
    socialIcons:
      - name: "email"
        url: "mailto:picozai@outlook.com"
      - name: "github"
        url: "https://github.com/PiktCai"
    ShowCodeCopyButtons: true
    env: production
menu:
  main:
    - identifier: about
      name: å…³äº
      url: /about/
      weight: 10
    - identifier: aya
      name: ã‚ã‚„
      url: /aya/
      weight: 20
    - identifier: poems
      name: æ—¶è¯­
      url: https://pikt.notion.site/527c87ef88694ffb919fd785048d12bf
      weight: 30
    - identifier: friends
      name: æœ‹å‹
      url: /friends/
      weight: 50
    - identifier: dialect
      name: ä¹¡éŸ³
      url: https://pikt.notion.site/ee53750c5dc14b44aaafafbef9f6fad5
      weight: 40
    - identifier: search
      name: ğŸ”
      url: /search/
      weight: 60
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
